DROP TABLE IF EXISTS SPACESHIPS;
CREATE TABLE SPACESHIPS (
    ID BIGINT auto_increment PRIMARY KEY COMMENT 'Spaceship Id',
    NAME VARCHAR(250) COMMENT 'Spaceship name'
);

DROP SEQUENCE IF EXISTS SPACESHIPS_SEQ;
CREATE SEQUENCE SPACESHIPS_SEQ START WITH 23 INCREMENT BY 1;