version: '3.9'
services:
  w2m-spaceships-spaceships:
    image: bgtibant/w2m-spaceships
    depends_on:
      - w2m-spaceships-rabbitmq
    environment:
      - RABBITMQ_HOST=w2m-spaceships-rabbitmq
    ports:
      - "8080:8080"

  w2m-spaceships-rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"